services:
  - type: web
    name: tournament-server
    env: node
    plan: free
    region: oregon
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: tournament-db
          property: connectionString
      - key: ADMIN_PASSWORD
        sync: false
        value: нуарли07

  - type: web
    name: tournament-client
    env: node
    plan: free
    region: oregon
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://tournament-server.onrender.com/api
      - key: NEXT_PUBLIC_SITE_URL
        value: https://tournament-client.onrender.com

databases:
  - name: tournament-db
    plan: free
    databaseName: tournament
    user: tournament_user
